# This file was generated by GoReleaser. DO NOT EDIT.
cask "treehouse" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "44844eeb9508f14e3ff90e6d5fb487fcd53ac6c4303aaa6cd0c1321cb97b8dd1"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9db6ea0bffbda378113016273494149300840d389acf4bcc2bdb42b6abdaa842"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e5e624041150fac985d253292a1e872a356baef8115f4e4efc263a2a460455c"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b7e280e883988804f3197df5a2661b8d356a87a9c17f85142497c3ec948f2a24"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_linux_arm64.tar.gz"
    end
  end

  name "treehouse"
  desc "Git worktree manager with config-driven placement"
  homepage "https://github.com/AirConditionedSoftware/treehouse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "th"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/th"]
    end
  end

  # No zap stanza required

end
