# This file was generated by GoReleaser. DO NOT EDIT.
cask "treehouse" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "e3203158a1e13d95886178914e5d86ac4ec1ad8b7895a23ce22bb30838f44988"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d36df3e16549f40e8d97c603ee4c089ea444ca24e2ecad7fd13770c11c23741"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c937de95ffbe7ab91696126870c5dd004831d19950a3db52d862a10697b7654"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b71a2486335a7fc3b52dd7cf478644d8fb836406b2bef794ee054438a2be8550"
      url "https://github.com/AirConditionedSoftware/treehouse/releases/download/v#{version}/treehouse_linux_amd64.tar.gz"
    end
  end

  name "treehouse"
  desc "Git worktree manager with config-driven placement"
  homepage "https://github.com/AirConditionedSoftware/treehouse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "th"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/th"]
    end
  end

  # No zap stanza required
end
