# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.2.11"

  on_macos do
    on_intel do
      sha256 "3552ed46afd2e0ac092f9619f421700e3a5b36f7d5752bbcf775f4e6e032daa0"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2777b8bfe9fa4eafec1edd1e4653246570a82045eb620f9fdbd71f84a1a2b549"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "02ba05518a0b99cdccac45eebbfaaf59fd92a584d92d9f7a19af5f47bbda79ba"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "985abd910e17876eb324ce1e529ce11d97a68cc9ab4cb2ef9a908014c28ee9d0"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Git worktree manager with config-driven placement"
  homepage "https://github.com/AirConditionedSoftware/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
