# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.2.13"

  on_macos do
    on_intel do
      sha256 "6ffced9faaaa1989049c351d50e5166e2c430424876ad8887b20a3d697d561bf"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5885cc6aecd6d2e3e09a0f72e4b50ba1f1ecd7d2d3c1face9457f781f507d069"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0be431c8e8161561b8ed270b76d3e35702479c4dc5bf7bc39159c735e4b3c6b"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d90231f2768d508810a0a831a10c519a2c1227438a4e9607983a4c2373783b3d"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Git worktree manager with config-driven placement"
  homepage "https://github.com/AirConditionedSoftware/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
