# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "84db8948ec7d6399a7d6e0e5bc802895c66f4e4dc76bd7e376a918a39b724c43"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "237d6cacb12a7248e7f15e23c7fcb4992d3723e624ab734964fb5cf6250867b4"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83610aacff5e28bdbc0e1bc91497db4ed53612dbca2c944e1602b496547d658a"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b387743ba0741ed8549773d72d7caa2035c201d4744a7927e2c693211c7e5bce"
      url "https://github.com/AirConditionedSoftware/wt/releases/download/v#{version}/wt_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Git worktree manager with config-driven placement"
  homepage "https://github.com/AirConditionedSoftware/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
